# Folders
source: source
destination: build

# Sass
sass:
  sass_dir: _sass
  style: :expanded

# Exclusions
exclude: ["bower_components", "vendor"]

# Collections
collections:
  notes:
    output: true

# Urls
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vadimbrodsky.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:title/
paginate: 20
paginate_path: 'page:num'

# Publish posts with future date.
future: false
timezone: America/Toronto

# Compile posts in the _drafts directory.
show_drafts: false

# Markdown library
markdown: redcarpet

# Markdown library options
redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables', 'autolink', 'with_toc_data', 'strikethrough']

# Plugins
# whitelist: []
gems:
  - 'bourbon'
  - 'neat'
  - 'jekyll-paginate'
  - 'jekyll-youtube'

github:
  repo: https://github.com/VadimBrodsky/vadimbrodsky.github.io

# Custom Vars
title: VB
title_expanded: Vadim Brodsky
author:
  name: Vadim Brodsky
  email: vadim.brodsky@gmail.com
tagline: Designer, Developer, Human
description: This a personal blog of Vadim Brodsky, disucssing design, development and all things remarkable.
twitter_username: vadimbrodsky
github_username:  vadimbrodsky

nav:
  Home:   '/'
  # Posts:  '/posts/'
  # Links:  '/links/'
  # Videos: '/videos/'
  Notes:  '/notes/'
  About:  '/about/'
