# Site settings
title: 'Vadim Brodsky'
author:
  name: Vadim Brodsky
  email: vadim.brodsky@gmail.com
tagline: 'Designer, Developer, Thinker'
description: "This a personal blog of Vadim Brodsky, disucssing design, development and all things remarkable."
baseurl: ""
url: "http://vadimbrodsky.github.io"
twitter_username: vadimbrodsky
github_username:  vadimbrodsky

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Publish posts with future date.
future: true

# Compile posts in the _drafts directory.
show_drafts: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables', 'autolink', 'with_toc_data']

github:
  repo:           https://github.com/VadimBrodsky/vadimbrodsky.github.io

# Custom vars
version:          1.0.0

# Collections
collections:
  notes:
    output: true

# Sass
sass:
  sass_dir: _sass
  style: :expanded

# Exclusions
exclude: ["bower_components"]
