# Site settings
title: Learning Simplicity
author:
  name: Vadim Brodsky
  email: vadim.brodsky@gmail.com 
description: "This a personal blog of Vadim Brodsky, disucssing design, development and all things remarkable."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: vadimbrodsky
github_username:  vadimbrodsky


source:      ./_src
destination: ./_site
plugins:     ./_src/_plugins
layouts:     ./_src/_layouts


# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Publish posts with future date.
future: true

# Compile posts in the _drafts directory.
show_drafts: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables', 'autolink']


