# Folders
source: source
destination: build

# Sass
sass:
  sass_dir: _sass
  style: :expanded

# Exclusions
exclude: ["bower_components"]

# Collections
collections:
  notes:
    output: true

# Urls
baseurl: ""
url: "http://vadimbrodsky.github.io"

# Site settings

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
# permalink: pretty
permalink: /:year/:month/:title

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'

# Publish posts with future date.
future: false
timezone: America/Toronto

# Compile posts in the _drafts directory.
show_drafts: false

# Markdown library
markdown: redcarpet

# Markdown library options
redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables', 'autolink', 'with_toc_data', 'strikethrough']

github:
  repo: https://github.com/VadimBrodsky/vadimbrodsky.github.io

# Custom Vars
title: VB
author:
  name: Vadim Brodsky
  email: vadim.brodsky@gmail.com
tagline: Designer, Developer, Thinker
description: This a personal blog of Vadim Brodsky, disucssing design, development and all things remarkable.
twitter_username: vadimbrodsky
github_username:  vadimbrodsky
version: 1.0.0
